production:
  options:
    raise_not_found_error: false
  sessions:
    default:
      database: rollfindr_prod
      hosts:
        - localhost:27017

development:
  options:
    raise_not_found_error: false
  sessions:
    default:
      database: rollfindr
      hosts:
        - localhost:27017
test:
  options:
    raise_not_found_error: false
  sessions:
    default:
      database: mongoid_test
      hosts:
        - localhost:27017
