production:
  clients:
    default:
      database: rollfindr_prod
      hosts:
        - services.bjjmapper.com:27017

development:
  clients:
    default:
      database: rollfindr
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: mongoid_test 
      hosts:
        - localhost:27017
